# vim:fileencoding=utf-8:foldmethod=marker

#: 窗口外观 {{{

lines 25

#: 面板中显示的行数。对 background、centered 和 vertical
#: 面板无效。如果值带有 px 后缀，则以像素为单
#: 位设置面板高度，而非行数。

columns 80

#: 面板中显示的列数。对 background、centered 和 horizontal
#: 面板无效。如果值带有 px 后缀，则以像素为单
#: 位设置面板宽度，而非列数。

edge center

#: 将面板放置在屏幕的哪个边缘。注意，某些窗口管理器
#: （如 i3）不支持将停靠窗口放置在左右边缘。
#: 值 background 表示将面板设为"桌面壁纸"。
#: 注意，使用 sway 时如果在 sway 配置中设置了背景，
#: 它会覆盖此 kitten 绘制的背景。
#: 此外还有三个值：center、center-sized 和 none。
#: 值 center 将面板锚定到所有边并覆盖整个显示器
#: （在 macOS 上为显示器未被标题栏和 Dock 覆盖的部分）。
#: 可以使用 margin 参数缩小和放置面板。
#: 值 none 将面板锚定到左上角，应使用 margin 参数来放置。
#: 其大小由 lines 和 columns 设置。
#: 值 center-sized 与 none 类似，只是面板居中而
#: 非在左上角，且 margin 无效。

background_opacity 0.85

#: 窗口的背景不透明度。此选项与 kitty 的同名选项工作方式相同，
#: 放在这里是因为快速访问终端有不同的默认值。

# hide_on_focus_loss no

#: 窗口失去键盘焦点时自动隐藏。
#: 使用此选项将强制 focus_policy 为 on-demand。

# grab_keyboard no

#: 抓取键盘。这意味着操作系统中定义的全局快捷键
#: 将被传递给 kitty。适用于想创建 OS 模态窗口的场景。
#: 实际效果取决于操作系统/窗口管理器/桌面环境。
#: 在 Wayland 上，仅当合成器实现了
#: inhibit-keyboard-shortcuts 协议时才有效
#: <https://wayland.app/protocols/keyboard-shortcuts-inhibit-unstable-v1>。
#: 在 macOS 上，Apple 不允许应用程序在没有特殊权限的情况下
#: 抓取键盘，因此无效。

# margin_left 0

#: 设置面板的左边距（像素）。对右侧面板无效。
#: 仅在 macOS 和支持 wlr layer shell 协议的
#: Wayland 合成器上有效。

# margin_right 0

#: 设置面板的右边距（像素）。对左侧面板无效。
#: 仅在 macOS 和支持 wlr layer shell 协议的
#: Wayland 合成器上有效。

# margin_top 0

#: 设置面板的上边距（像素）。对底部面板无效。
#: 仅在 macOS 和支持 wlr layer shell 协议的
#: Wayland 合成器上有效。

# margin_bottom 0

#: 设置面板的下边距（像素）。对顶部面板无效。
#: 仅在 macOS 和支持 wlr layer shell 协议的
#: Wayland 合成器上有效。

# kitty_conf

#: 绘制窗口时使用的 kitty 配置文件路径。
#: 可多次指定。默认使用正常的 kitty.conf。
#: 相对路径相对于 kitty 配置目录解析。

# kitty_override

#: 覆盖单个 kitty 配置选项，可多次指定。
#: 语法：kitty_override name=value。例如：
#: kitty_override font_size=20。

# app_id kitty-quick-access

#: 在 Wayland 上设置 layer shell surface 的命名空间。
#: 在 X11 上设置分配给快速访问窗口的 WM_CLASS。（仅 Linux）

# output_name

#: 面板一次只能显示在单个显示器（输出）上。
#: 此选项允许你按名称指定使用哪个输出。
#: 如果未指定，合成器将自动选择输出，
#: 通常是用户最后交互的输出或主显示器。
#: 运行 kitten panel --output-name list 获取可用输出列表。
#: 使用 listjson 获取 JSON 编码的输出。
#: 注意，在 Wayland 上输出只能在面板创建时设置，
#: 创建后无法更改，也无法在所有输出上显示单个面板。
#: 请向 Wayland 开发者抱怨这一点。

# start_as_hidden no

#: 是否在启动时隐藏快速访问终端。
#: 如果你在系统启动时启动它，此选项很有用。

# focus_policy exclusive

#: 在支持 wlr layer shell 协议的 Wayland 合成器上，
#: 指定面板键盘交互的焦点策略。
#: 更多细节请参考 wlr layer shell 协议文档。
#: 注意，不同 Wayland 合成器在 exclusive 模式下的行为差异很大，
#: 你的体验可能有所不同。
#: 在 macOS 上，exclusive 和 on-demand 目前是相同的。

#: }}}
