git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editPreset: 'nvim'

keybinding:
  universal:
    # 'Files' appended for legacy reasons
    pushFiles: P

    # 'Files' appended for legacy reasons
    pullFiles: U
