[option]
re_forbidden_localparam = "^[^p](UNCONFIGURED|.*)$"
re_forbidden_parameter = "^[^p](UNCONFIGURED|.*)$"
generate_if_with_label = "gen_"

[textrules]
header_copyright = false
style_directives = true
style_semicolon = false
style_textwidth = false

[syntaxrules]
style_indent = false
action_block_with_side_effect = true
blocking_assignment_in_always_at_edge = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = true
default_nettype_wire_at_end = true
enum_with_type = true
eventlist_comma_always_ff = true
explicit_brackets_for_confusing_precedence = true
explicit_case_default = true
function_same_as_system_function = false
function_with_automatic = true
general_always_level_sensitive = true
general_always_no_edge = false
genvar_declaration_in_loop = false
genvar_declaration_out_loop = true
implicit_case_default = true
inout_with_tri = false
input_with_var = false
interface_identifier_matches_filename = true
interface_port_with_modport = false
keyword_forbidden_always = false
keyword_forbidden_always_comb = false
keyword_forbidden_always_ff = false
keyword_forbidden_always_latch = false
keyword_forbidden_generate = false
keyword_forbidden_logic = false
keyword_forbidden_wire_reg = false
keyword_required_generate = true
localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = true
loop_variable_declaration = true
module_ansi_forbidden = false
# module_identifier_matches_filename = true
multiline_for_begin = true
multiline_if_begin = true
non_blocking_assignment_in_always_no_edge = true
operator_incdec = false
operator_self_assignment = false
output_with_var = false
package_identifier_matches_filename = true
package_item_not_in_package = true
parameter_default_value = true
parameter_explicit_type = true
parameter_type_twostate = true
procedural_continuous_assignment = true
generate_case_with_label = false

generate_if_with_label = true
prefix_instance = true
prefix_interface = true
re_forbidden_assert = true
re_forbidden_assert_property = true
re_forbidden_localparam = true
re_forbidden_parameter = true
re_forbidden_property = true
re_forbidden_sequence = true
# style_commaleading = false
style_keyword_0or1space = false
